name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: Backend/UserService

      - name: Run tests
        run: npm test
        working-directory: Backend/UserService

      - name: Build Docker image
        run: docker build -t user-service:latest .
        working-directory: Backend/UserService

      - name: Push Docker image
        run: |
          docker tag user-service:latest your-docker-repo/user-service:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-docker-repo/user-service:latest
