name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: Backend/HealthDataService

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
        working-directory: Backend/HealthDataService

      - name: Build Docker image
        run: docker build -t health-data-service:latest .
        working-directory: Backend/HealthDataService

      - name: Push Docker image
        run: |
          docker tag health-data-service:latest your-docker-repo/health-data-service:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-docker-repo/health-data-service:latest
